name: docker-build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: jemand771/docker-build-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          push: false
  build-uploader:
    runs-on: ubuntu-latest
    steps:
      - uses: jemand771/docker-build-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ghcr.io/${{ github.repository }}-uploader
          file: uploader.Dockerfile
          push: false
  push-images:
    runs-on: ubuntu-latest
    needs:
      - build-server
      - build-uploader
    steps:
      - name: push-server
        uses: jemand771/docker-build-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push-uploader
        uses: jemand771/docker-build-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ghcr.io/${{ github.repository }}-uploader
          file: uploader.Dockerfile
