name: docker-build
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PLATFORMS: linux/amd64

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: jemand771/docker-build-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          platforms: ${{ env.PLATFORMS }}
          push: false
  build-uploader:
    runs-on: ubuntu-latest
    steps:
      - uses: jemand771/docker-build-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ghcr.io/${{ github.repository }}-uploader
          file: uploader.Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: false
  push-images:
    runs-on: ubuntu-latest
    steps:
      - name: push-server
        uses: jemand771/docker-build-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          platforms: ${{ env.PLATFORMS }}
      - name: push-uploader
        uses: jemand771/docker-build-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ghcr.io/${{ github.repository }}-uploader
          file: uploader.Dockerfile
          platforms: ${{ env.PLATFORMS }}
